In [4]:
import numpy as np

In [5]:
A=np.array([[1, 2, 3, 4, 5],[6,8,10,12,14],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])

In [6]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  8, 10, 12, 14],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [7]:
A-A[:,0][:,np.newaxis]

array([[0, 1, 2, 3, 4],
       [0, 2, 4, 6, 8],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [8]:
A[:,-1]-A[:,0]

array([4, 8, 4, 4, 4])

In [9]:
A/(A[:,-1]-A[:,0])[:,np.newaxis]-1


array([[-0.75, -0.5 , -0.25,  0.  ,  0.25],
       [-0.25,  0.  ,  0.25,  0.5 ,  0.75],
       [ 1.75,  2.  ,  2.25,  2.5 ,  2.75],
       [ 3.  ,  3.25,  3.5 ,  3.75,  4.  ],
       [ 4.25,  4.5 ,  4.75,  5.  ,  5.25]])

In [10]:
A[:,:2]

array([[ 1,  2],
       [ 6,  8],
       [11, 12],
       [16, 17],
       [21, 22]])

In [11]:
A[:,2:4]

array([[ 3,  4],
       [10, 12],
       [13, 14],
       [18, 19],
       [23, 24]])

In [12]:
A[:,2:4].shape

(5, 2)

In [13]:
a=np.array([[1,2],[3,4],[5,6]])
b=np.array([[0.5,2],[0.6,3],[7,8]])

In [14]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [15]:
b

array([[0.5, 2. ],
       [0.6, 3. ],
       [7. , 8. ]])

In [16]:
2*a*b


array([[ 1. ,  8. ],
       [ 3.6, 24. ],
       [70. , 96. ]])

In [21]:
np.random.seed(0)
A=np.random.rand(5,5)
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
(A-A[:,0][:,np.newaxis])

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [23]:
(A[:,-1]-A[:,0])

array([2, 2, 2])

In [24]:
(A-A[:,0][:,np.newaxis])/(A[:,-1]-A[:,0])[:,np.newaxis]-1

array([[-1. , -0.5,  0. ],
       [-1. , -0.5,  0. ],
       [-1. , -0.5,  0. ]])

In [25]:
import numpy as np

A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
# 按列优先展开，模拟 MATLAB 的线性索引
A_fortran = A.flatten('F')
# MATLAB 中 A(1) 为第一个元素，A(3) 为第三个元素（即 7）
result = (A - A_fortran[0]) / (A_fortran[2] - A_fortran[0]) - 1
print(result)


[[-1.         -0.83333333 -0.66666667]
 [-0.5        -0.33333333 -0.16666667]
 [ 0.          0.16666667  0.33333333]]
